version: '3.1'

services:

  mysql-database:
    image: mysql
    container_name: wed_database
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  spring-boot-app:
    image: springboot-docker-container
    container_name: wed_backend
    ports:
      - "8080:8080"
    build:
      context: './'
      dockerfile: 'Dockerfile'
    restart: always
    depends_on:
      - mysql-database
