version: '3'

services:
  wed_database_mysql:
    image: mysql
    container_name: wed_database
    environment:
      - MYSQL_DATABASE=wed_composer
      - MYSQL_ROOT_PASSWORD=S9cyS.qE)*kK)vqj
      - MYSQL_ALLOW_EMPTY_PASSWORD=
      - MYSQL_RANDOM_ROOT_PASSWORD=
    ports:
      - 3306:3306
    expose:
      - 3306
    command: --default-authentication-plugin=mysql_native_password
#    --init-file /app/database/init.sql
#    volumes:
#      - ./init.sql:/app/database/init.sql
    restart: always

  wed_spring_backend:
    image: springboot
    container_name: wed_backend
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - wed_database_mysql
  wed-react-frontend:
    image: node:16.13.2
    container_name: wed_frontend
    build:
      context: './web'
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - wed_spring_backend

